//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestExt.ConsoleApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.zhongdengwang.org.cn/mfrs_ws_test/services/LoginService")]
        public string MyTestExt_ConsoleApp_cn_org_zhongdengwang_ws_LoginService_WSLoginServiceService {
            get {
                return ((string)(this["MyTestExt_ConsoleApp_cn_org_zhongdengwang_ws_LoginService_WSLoginServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.zhongdengwang.org.cn/mfrs_ws_test/services/InitRegisterService")]
        public string MyTestExt_ConsoleApp_cn_org_zhongdengwang_ws_InitRegisterService_WSInitRegisterServiceService {
            get {
                return ((string)(this["MyTestExt_ConsoleApp_cn_org_zhongdengwang_ws_InitRegisterService_WSInitRegisterSe" +
                    "rviceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsquery.zhongdengwang.org.cn/mfrsq_ws_test/services/queryBySubject")]
        public string MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_QueryBySubject_WSQueryBySubjectServiceService {
            get {
                return ((string)(this["MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_QueryBySubject_WSQueryBySubject" +
                    "ServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsquery.zhongdengwang.org.cn/mfrsq_ws_test/services/login")]
        public string MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_Login_WSLoginServiceService {
            get {
                return ((string)(this["MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_Login_WSLoginServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsquery.zhongdengwang.org.cn/mfrsq_ws_test/services/queryDownLoadFileByNu" +
            "m")]
        public string MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_QueryDownLoadFileByNum_WSDownLoadFileByNumServiceService {
            get {
                return ((string)(this["MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_QueryDownLoadFileByNum_WSDownLo" +
                    "adFileByNumServiceService"]));
            }
        }
    }
}
