//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace MyTestExt.ConsoleApp.cn.org.zhongdengwang.wsquery.QueryDownLoadFileByNum {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSDownLoadFileByNumServiceServiceSoapBinding", Namespace="https://wsquery.zhongdengwang.org.cn/mfrsq_ws/services/DownLoadFileByNumService")]
    public partial class WSDownLoadFileByNumServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryDownLoadFileByNumOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSDownLoadFileByNumServiceService() {
            this.Url = global::MyTestExt.ConsoleApp.Properties.Settings.Default.MyTestExt_ConsoleApp_cn_org_zhongdengwang_wsquery_QueryDownLoadFileByNum_WSDownLoadFileByNumServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryDownLoadFileByNumCompletedEventHandler queryDownLoadFileByNumCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://wsquery.zhongdengwang.org.cn/mfrsq_ws/services/DownLoadFileByNumService", ResponseNamespace="https://wsquery.zhongdengwang.org.cn/mfrsq_ws/services/DownLoadFileByNumService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] queryDownLoadFileByNum([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] platformAuthCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] loginToken, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] registerNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] debttype, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] nameorno) {
            object[] results = this.Invoke("queryDownLoadFileByNum", new object[] {
                        platformAuthCode,
                        loginToken,
                        registerNo,
                        debttype,
                        nameorno});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void queryDownLoadFileByNumAsync(byte[] platformAuthCode, byte[] loginToken, byte[] registerNo, byte[] debttype, byte[] nameorno) {
            this.queryDownLoadFileByNumAsync(platformAuthCode, loginToken, registerNo, debttype, nameorno, null);
        }
        
        /// <remarks/>
        public void queryDownLoadFileByNumAsync(byte[] platformAuthCode, byte[] loginToken, byte[] registerNo, byte[] debttype, byte[] nameorno, object userState) {
            if ((this.queryDownLoadFileByNumOperationCompleted == null)) {
                this.queryDownLoadFileByNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryDownLoadFileByNumOperationCompleted);
            }
            this.InvokeAsync("queryDownLoadFileByNum", new object[] {
                        platformAuthCode,
                        loginToken,
                        registerNo,
                        debttype,
                        nameorno}, this.queryDownLoadFileByNumOperationCompleted, userState);
        }
        
        private void OnqueryDownLoadFileByNumOperationCompleted(object arg) {
            if ((this.queryDownLoadFileByNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryDownLoadFileByNumCompleted(this, new queryDownLoadFileByNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void queryDownLoadFileByNumCompletedEventHandler(object sender, queryDownLoadFileByNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryDownLoadFileByNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryDownLoadFileByNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591